name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1

    - name: Install dependencies
      run: npm run bootstrap
    
    - name: Build @fretnot/playground
      working-directory: packages/playground
      run: npm run build

    - name: Publish @fretnot/playground
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: packages/playground/dist

    - name: Build @fretnot/api
      working-directory: packages/api
      run: npm run build

    - name: Publish @fretnot/api
      working-directory: packages/api
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:login
        heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
        heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web

    - name: Publish @fretnot/fretboard
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
